name: Next JS Build with Artifacts and chache

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
      - name: Setup Node JS
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install Dependancies
        run: npm install
      - name: Build Next JS App
        run: npm run build

      - name: Upload Build on Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: nextjs-build
          path: out/
          
